export const electiveData = [
  {
    name: "7/8 Intro Coding",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7 Art",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Photography",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 STEM",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Drama",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  // {
  //   name: "7/8 Creative Writing",
  //   length: 0.5,
  // },
  {
    name: "7/8 Keyboarding",
    length: 0.5,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Band",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Choir",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Advanced Coding",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Guitar",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7/8 Strings",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
  {
    name: "7 Spanish",
    length: 1,
    check: false,
    chosen: false,
    firstAlt: false,
    secondAlt: false,
  },
];
